# Generated by Django 2.2.2 on 2019-06-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=125)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=125)),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Room')),
            ],
        ),
    ]
