# Generated by Django 2.2.2 on 2019-06-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(default=242246836546410756283078678854314477057),
        ),
    ]
