# Generated by Django 2.2.2 on 2019-06-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='b63f0b2c3d253875b11f2b1f70cbc601', max_length=32),
        ),
    ]
