# Generated by Django 2.2.2 on 2019-06-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_auto_20190628_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='242246836546410756283078678854314477057', max_length=39),
        ),
    ]
