# Generated by Django 2.2.2 on 2019-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_auto_20190628_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='description',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(blank=True, max_length=39),
        ),
    ]
