# Generated by Django 2.2.2 on 2019-06-30 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_presentation_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='presenter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='attend_presentations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='conference.Presentation'),
        ),
    ]
