# Generated by Django 2.2.2 on 2019-06-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_auto_20190630_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(blank=True, max_length=39),
        ),
    ]
