# Generated by Django 2.2.2 on 2019-06-30 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_auto_20190630_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attend_presentations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='conference.Presentation'),
        ),
    ]
