# Generated by Django 2.2.2 on 2019-06-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_auto_20190630_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='attend_presentations',
        ),
        migrations.AddField(
            model_name='profile',
            name='attend_presentations',
            field=models.ManyToManyField(blank=True, null=True, to='conference.Presentation'),
        ),
    ]
