# Generated by Django 2.2.2 on 2019-06-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0015_auto_20190630_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='attend_presentations',
            field=models.ManyToManyField(blank=True, to='conference.Presentation'),
        ),
    ]
