# Generated by Django 2.2.2 on 2019-07-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_auto_20190630_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='event_id',
            field=models.UUIDField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.UUIDField(blank=True),
        ),
    ]
