# Generated by Django 2.2.2 on 2019-07-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0017_auto_20190701_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.UUIDField(blank=True),
        ),
    ]
