# Generated by Django 2.2.2 on 2019-07-01 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0018_auto_20190701_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_id',
        ),
    ]
