# Generated by Django 2.2.2 on 2019-07-01 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0019_auto_20190701_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Room'),
        ),
    ]
