# Generated by Django 2.2.2 on 2019-07-02 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0021_presentation_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='presenter',
        ),
        migrations.AddField(
            model_name='presentation',
            name='presenters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
